Initial a new module
terraform-alicloud-modules/terraform-alicloud-enable pull request #1
Opened 2022-03-14 09:00 UTC by Wanghx0991

2022-03-14 12:18 UTC, xiaozhu36 requested changes

2022-03-14 12:18 UTC, xiaozhu36 commented on variables.tf
> +variable "product_enabled" {
既然上面用的是 service name，那么这个参数就改成 services 吧

2022-03-14 12:18 UTC, xiaozhu36 commented on variables.tf
> +  description = ""
描述都补充上

2022-03-14 12:18 UTC, xiaozhu36 commented on README.md
> +}
这个地方要作为实例写上几个要开通的服务的示例

2022-03-17 07:15 UTC, Wanghx0991 commented on variables.tf
> +variable "product_enabled" {
Done

2022-03-18 12:43 UTC, xiaozhu36 requested changes

2022-03-18 12:43 UTC, xiaozhu36 commented on README.md
> +}
这个还是没改啊

2022-03-18 12:43 UTC, xiaozhu36 commented on README.md
> +}
这个地方没必要跟上面的Usage分开，用一个就行了

2022-03-18 12:43 UTC, xiaozhu36 commented on README.md
> +}
另外，cr_pwd是一个单独的参数啊，是要放在services 外面的

2022-03-24 03:39 UTC, Wanghx0991 commented on README.md
> +}
Done 加了一个三级标题在下面

2022-03-24 03:43 UTC, Wanghx0991 commented on README.md
> +}
Done

2022-03-24 06:25 UTC, merged